### ISSUE TITLE
일감 정리

### ISSUE THREAD

**Issue by dongwu-kim** [dongwu-kim/soomgo_wecode_commuting_app#11]
# _진행예정 사항_

### 상단 블럭 (score : 13)

- 근무시간 표시하기(출, 근, 퇴) 

### 이번주 근무 (score : 21)

- 테이블 내 당일 시간 변경 구현하기
- 날짜 요일 Date 계산하기 
- 계산된 값으로 DB 데이터 불러오기
- 계산된 범위 내 근무시간 표시하기
- 시간별 상태bar 색상 변경 구현하기
- 공휴일 제외 로직 구현하기

### 1주 평균 근로시간 (score : 21)

- DatePicker 구현하기
- 선택범위 data DB에서 가져오기
- 가져온 근무시간 데이터 평균값으로 치환하기
- 시간별 상태bar 색상 변경 구현하기

## 출퇴근 상세 view (score : 8 )

DatePicker 구현하기
DB에서 해당 Date 범위 data 가져오기
가져온 data 기반 렌더링

---

# _완료한 사항_

## DB
- DB mock json 설계 => 진행에 따라 수정될 수 있음

### 전체 (score : 5)

- 퍼블리싱(로고 이미지) => Hugo 
- Google auth 연동하기 => Steve
- Google auth 유효성 검사하기 => Milo & Hugo

### 상단 블럭 (score : 13)

- Today date 표시하기 ✔️
- 위치 표시하기 ✔️
- 출근 toggle button 작성하기 ✔️
- 출퇴근 기록 button (stack - nav) ✔️
- 근무일지 작성 button (stack - nav) ✔️
- DB에 출퇴근 data 저장하기 ✔️

## 근무일지 view (score : 13)

- Text 제한하기 ✔️
- 실시간으로 당일, 전일 데이터 관리하는 로직 작성하기 ✔️
    - 00:00 기준 오늘 할일 => 어제 한 일 이동
    - DB load
- 저장하기 (DB save) 버튼 구현 ✔️
- 터치 시 수정기능 (DB update) ✔️

**Comment by pratt3351** [comment]
- 인트로 페이지 + google login : 5점
- 출퇴근 화면
    - 메인 화면에서의 이름 표시 : 1점
    - 출퇴근 기능 상단 섹션 : 13점
    - 이번주 근무 : 21점
    - 1주 평균 근로시간 : 21점
- 근무일지 작성/수정화면 : 13점
- 근무 로그 리스트 : 8점
